version: '2'
services:
   dev:
     image: node:9.6.1
     command: bash
     user: '1000:1000'
     volumes:
       - .:/app
     working_dir: /app
     ports:
       - '9229:9229'
   server:
     image: node:9.6.1
     command: node_modules/.bin/nodemon src/server/index.js
     working_dir: /app
     volumes:
       - .:/app
     ports:
       - '8000:80'
   mongo:
     image: mongo:3.6
